### PR TITLE
!U: Added beautification to product documentation

### PR DESCRIPTION
**Pull request by gvyshnya**
- applied styling to make the product documentation (doc.html) to resemble https://dataversioncontrol.com/ by its look and feel

### CODE REVIEW

**Comment by dmpetrov** [comment]
@gvyshnya thank you for the patch. It looks much better.

But there is still a difference in colors and indentation (from left\right as well as from top):

screen shot 2017-10-17 at 8 52 04 pm
screen shot 2017-10-17 at 8 52 07 pm

Is it possible to make the header look exactly like the header on dataversioncontrol.com?

**Comment by dmpetrov** [comment]
Also, there are a lot of small issues with code climate: https://codeclimate.com/github/dataversioncontrol/dvc/pull/255

**Comment by gvyshnya** [comment]
I have just applied a number of css changes to make the look and feel of doc.html close to https://dataversioncontrol.com/ as much as possible

**Comment by dmpetrov** [comment]
Thank you @gvyshnya 
It looks better, almost line the dvc home page.

However, there are still some descriptencies in the header:
1. The image color schema does not match the dvc one
2. The front does not match as well "Make your data science projects reproducible".
3. Logo has very small resolution, is it possible to use the link to the original logo: https://dataversioncontrol.com/logo.png
4. The image on the DVC page has no indentations on the top and on the sides.
5*. There are still a lot of small codeclimat issues which are supposed to be straightforward how to fix.

**Comment by gvyshnya** [comment]
I have applied fixes as per your earlier bug report in the comments above.

**Notes:**
- the request to match the fonts in the header exactly to what is displayed in the public site required to add binaries of a non-standard non-Google Web font (namely, _medium-content-sans-serif-font_), to style.css (as it had been implemented in css of the public web site)
- this introduced the new type of codeclimate issue - "@font-face declaration doesn't follow the fontspring bulletproof syntax" (7 instances of this issue detected)
- it cannot be fixed since we have the font declaration as a binary source (moreover, it might theoretically affect only users of IE9 or earlier, which are so rare as of Nov 2017)

**Comment by gvyshnya** [comment]
I have just fixed the minor styling issue reported by @dmpetrov earlier (namely, text "Make your data science ..." does not align with "Data Version Control" text). Could you please review and share your feedback?

**Comment by dmpetrov** [comment]
Thank you @gvyshnya . Merged!

**Pull request merged**
