### PR TITLE
[WIP] Misc changes for build and testing

### PR DESCRIPTION
**Pull request by efiop**

### CODE REVIEW

**Comment by dmpetrov** [comment]
@efiop Are you still working on this?
Let's mark not completely ready pull requests as [WIP] - Work-In-Progress.

**Comment by efiop** [comment]
@dmpetrov Yes, sorry, unittests are now complaining on Python3. Just a few more iterations, sorry for the noise. I will merge it myself when it is ready.

**Comment by dmpetrov** [comment]
Noise is totally fine. I like to work in an existing pull request especially when Travis runs test automatically for each commit.
Just mark it as WIP.

**Comment by efiop** [comment]
@dmpetrov already marked.

**Comment by efiop** [comment]
It is finally fixed. Sorry for the noise. Merging...

**Pull request merged**
