### PR TITLE
Bugfixes and fsck refactoring

### PR DESCRIPTION
**Pull request by dmpetrov**
Note, now `fsck` outputs only files with conflicts. It can output everything by `--all` option.

### CODE REVIEW

**Comment by efiop** [comment]
This patch is great, thanks! If you don't mind, I'll first merge #395 and then rebase and merge this one.

**Comment by efiop** [comment]
Nevermind, merged already.

**Comment by dmpetrov** [comment]
I was working on unit-tests :(
I'll submit in a separate PR.

**Comment by efiop** [comment]
Oops, sorry for that.

**Pull request merged**
