### PR TITLE
specify dvc config root dir as enviroment variable

### PR DESCRIPTION
**Pull request by ophiry**
implements: https://github.com/dataversioncontrol/dvc/issues/169

allows using an environment variable DVC_ROOT to specify the location of the dvc config files
the location will be: <git>/DVC_ROOT/.dvc

this is useful for cases where a git repo is used for more then one project

### CODE REVIEW

**Comment by efiop** [comment]
Shouldn't we act like git does and look for .dvc up the directory tree?

**Comment by ophiry** [comment]
I usually prefer the more explicit approaches - specifying the specific directory, rather then relying on current directory

**Comment by efiop** [comment]
Would git-like behavior suit you? If it will, lets do it git-way, as we try to follow git logic in dvc.

**Comment by efiop** [comment]
There is no reason we can't have both though, if that really solves the problem much better than git approach =) Just wondering if git-like "up tree search" would suit you too.

**Comment by ophiry** [comment]
yes (I assume that the explicit setting will override the implicit setting)

**Comment by ophiry** [comment]
No longer relevant with the new version, where there's no specific data directory

**Pull request closed without merging**
