### PR TITLE
git: save and use target commit in state files

### LINKED ISSUE #193: dvc repro unable to identify changes after fast forward merge
```
$ git checkout first_model
$ git merge input_25K
$ dvc repro
Reproduction is not required for data item "data/eval_auc.txt".
```
Even though, Posts.tgz file was changed.

UPDATE: The issue is in `get_target_commit()` code which takes the last target file commit and compares that with the head. Instead, it should take the last target file commit in **a current branch**.

### PR DESCRIPTION
**Pull request by efiop**
Fixes #193

Signed-off-by: Ruslan Kuprieiev <kupruser@gmail.com>

### CODE REVIEW

**Comment by efiop** [comment]
Wrong, need to check if last commit is merge and only then use this.

**Comment by efiop** [comment]
Hm... Still wrong. Described issue occurs when HEAD is at commit that is a 'merge'(that affected target file), so dvc doesn't see any changes between HEAD and last commit that affected target file.

**Comment by dmpetrov** [comment]
Could you please describe what are you trying to do by this change?

**Comment by efiop** [comment]
@dmpetrov Sorry, those were notes to myself =) If I was able to reproduce it correctly, the issue happens when dependent file was modified by merge and that commit is your current HEAD. So basically get_target_commit reports some 'sha' and git log reports the same 'sha', thus your 'global_chages' becomes empty. To resolve that, we now check if last commit is 'merge' and if it is current 'HEAD' and if so, we return last commit _before_ merge.

If you have time, I would much appreciate if you could try out this pull-request to see if it solves your original issue, just to make sure.

**Comment by dmpetrov** [comment]
I'll try that. But I don't expect it completely solves the issue. The main reason - there are no merge commits for fast-forward merges (by default).

It looks like we have to keep sha-s of all dependencies in state files.

**Comment by efiop** [comment]
@dmpetrov Sorry, I edited my comment. Please don't try this yet, I'm still in the progress.

**Comment by efiop** [comment]
Yeah, I'm already working on storing commit sha in state file =). Thank you.

**Pull request merged**
